version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_coop
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:password@db/mini_coop
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm install && npm run build && npx serve -s build"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
